name: publish autodoc

on:
  workflow_call:
    inputs:
      version:
        required: false
        description: "version override"
        type: string

jobs:
  generate-and-deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eclipse-edc/.github/.github/actions/setup-build@main

      - name: Override version if input is set
        if: "${{ github.event.inputs.version != '' }}"
        run: sed -i "s/version=.*/version=${{ github.event.inputs.version }}/g" gradle.properties

      - name: Generate docs
        run: ./gradlew autodoc
      - name: Merge manifests
        run: ./gradlew mergeManifests
      - name: Render markdown
        run: |
          ./gradlew doc2md
          cp build/*.md build/manifest.md

      - name: extract version
        run: echo "VERSION=$(grep version= gradle.properties | cut -c 9-)" >> $GITHUB_ENV

      - name: Prepare deploy folder
        run: |
          mkdir -p deploy/autodoc/${{ env.VERSION }}

      - name: Render html
        uses: docker://pandoc/core:latest
        with:
          args: --standalone --from gfm --to html --output deploy/autodoc/${{ env.VERSION }}/index.html build/manifest.md

      - name: Render html for stable version
        if: ${{ !endsWith( env.VERSION, '-SNAPSHOT') }}
        run: cp deploy/autodoc/${{ env.VERSION }}/index.html deploy/autodoc/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: deploy
          keep_files: true
